import { KIT_COPY } from './kitCopy.js';

// Academy copy, separate from the sandbox and site dictionaries.
// Tuples are always [English, Russian, Uzbek]; pin/terminal IDs are literal.
const ui = {
 academy:['Academy','Академия','Akademiya'], subtitle:['Small experiments. Real discoveries.','Маленькие опыты. Настоящие открытия.','Kichik tajribalar. Haqiqiy kashfiyotlar.'],
 library:['Library','Библиотека','Kutubxona'], lessons:['Lessons','Уроки','Darslar'], close:['Close Academy','Закрыть академию','Akademiyani yopish'],
 search:['Find a part','Найти деталь','Detalni topish'], all:['All parts','Все детали','Barcha detallar'], structure:['Structure','Конструкция','Konstruksiya'], electronics:['Electronics','Электроника','Elektronika'], components:['Components','Компоненты','Komponentlar'],
 purpose:['What it does','Для чего нужна','Vazifasi'], connects:['What it connects to','С чем соединяется','Nimaga ulanadi'], pins:['Pins & power','Контакты и питание','Pinlar va quvvat'],
 mistake:['Watch out','Частая ошибка','Ehtiyot bo‘ling'], try:['Try it yourself','Попробуй сам','O‘zingiz sinab ko‘ring'], why:['Why it works','Почему это работает','Nega bu ishlaydi'],
 place:['Pick up this part','Взять деталь','Detalni olish'], focus:['Find in my build','Найти в моей модели','Modelimdan topish'], wiring:['Open wiring','Открыть проводку','Simlarni ulash'], program:['Open blocks','Открыть блоки','Bloklarni ochish'],
 plan:['Follow the wire','Проследи провод','Sim yo‘lini kuzating'], planHint:['Tap a route to trace its ends. Connect the real wires yourself.','Нажми на провод и найди его концы. Настоящие провода подключаешь ты.','Uchlarini ko‘rish uchun yo‘lni bosing. Haqiqiy simlarni o‘zingiz ulang.'],
 powerRoute:['Power for the module','Питание модуля','Modul quvvati'], groundRoute:['Shared electrical reference','Общая точка отсчёта','Umumiy elektr nuqtasi'], trigRoute:['Starts the sound pulse','Запускает звуковой импульс','Tovush impulsini boshlaydi'], echoRoute:['Returns the echo timing','Возвращает время эха','Aks-sado vaqtini qaytaradi'], outRoute:['Measurement to the board','Измерение поступает на плату','O‘lchov plataga uzatiladi'],
 start:['Start experiment','Начать опыт','Tajribani boshlash'], resume:['Continue experiment','Продолжить опыт','Tajribani davom ettirish'], next:['Check & next','Проверить и дальше','Tekshirish va keyingisi'], finish:['Check & finish','Проверить и завершить','Tekshirish va yakunlash'], back:['Previous step','Предыдущий шаг','Oldingi qadam'], backLessons:['All experiments','Все опыты','Barcha tajribalar'],
 current:['Your next move','Твой следующий шаг','Keyingi qadamingiz'], ready:['Verified — press Next to record this step.','Проверено — нажми «Дальше», чтобы сохранить шаг.','Tekshirildi — qadamni saqlash uchun keyingi tugmani bosing.'], waiting:['Waiting for this action in your build.','Ждём это действие в твоей модели.','Modelingizda shu amal bajarilishini kutmoqda.'],
 done:['Experiment complete!','Опыт завершён!','Tajriba yakunlandi!'], doneBody:['Every step checked. Keep experimenting!','Все шаги проверены. Продолжай экспериментировать!','Barcha qadamlar tekshirildi. Tajribalarni davom ettiring!'], completed:['Completed','Завершено','Bajarilgan'],
 saved:['Progress saved on this device','Прогресс сохранён на устройстве','Natija shu qurilmada saqlandi'], unsaved:['Storage unavailable. Progress lasts for this session.','Хранилище недоступно. Прогресс останется в этой сессии.','Saqlash imkonsiz. Natija shu seansda qoladi.'],
 noResults:['No matching parts. Try another name.','Детали не найдены. Попробуй другое название.','Detal topilmadi. Boshqa nomni sinang.'],
 noPins:['No electrical pins: a mechanical connection.','Электрических контактов нет: механическое соединение.','Elektr pinlari yo‘q: mexanik birikma.'],
 stopFirst:['Stop the simulation before placing parts.','Останови симуляцию перед добавлением деталей.','Detal qo‘shishdan avval simulyatsiyani to‘xtating.'],
 prerequisite:['Add an Arduino and a suitable mount first.','Сначала добавь Arduino и подходящее крепление.','Avval Arduino va mos mahkamlagich qo‘shing.'],
 unavailable:['This part is not available in this version.','Эта деталь недоступна в этой версии.','Bu detal ushbu versiyada yo‘q.'],
 starter:['Optional starter build','Готовая основа (по желанию)','Tayyor model (ixtiyoriy)'], starterNote:['Starting a lesson keeps your model and code. A starter replaces both after confirmation.','Урок сохраняет модель и код. Готовая основа заменяет их после подтверждения.','Dars model va kodni saqlaydi. Tayyor model ikkalasini tasdiqdan so‘ng almashtiradi.'],
 confirmTitle:['Replace this build and program?','Заменить модель и программу?','Model va dastur almashtirilsinmi?'], confirmBody:['Save your work first to keep it. The starter also replaces your wires.','Сначала сохрани работу. Готовая основа заменит и провода.','Ishingizni avval saqlang. Tayyor model simlarni ham almashtiradi.'],
 replace:['Replace with starter','Заменить готовой основой','Tayyor model bilan almashtirish'], cancel:['Keep my build','Оставить мою модель','Modelimni saqlab qolish'],
 lessonIntro:['Build a little. Notice a lot.','Собирай. Замечай. Понимай.','Yig‘ing. Kuzating. Tushuning.'], lessonSub:['Five experiments, checked against your own machine.','Пять опытов с проверкой твоей машины.','Mashinangizda tekshiriladigan beshta tajriba.'],
 step:['Step','Шаг','Qadam'], experiment:['Experiment','Опыт','Tajriba'],
 connectionReady:['Circuit ready','Цепь готова','Zanjir tayyor'], connectionMissing:['Check the wiring plan','Проверь схему подключения','Ulanish rejasini tekshiring'],
 sensorLabel:['SENSOR','ДАТЧИК','SENSOR'], finishGesture:['Finish or cancel the current placement or wire first.','Сначала заверши или отмени текущее размещение или провод.','Avval joriy detal joylashuvi yoki simni yakunlang yoxud bekor qiling.'],
 sensorLab:['Select this part to see live readings in the sensor lab.','Выбери деталь: показания доступны в лаборатории датчиков.','Detalni tanlang: jonli o‘lchovlar sensor laboratoriyasida.'],
};
const hole=['Bolts through aligned chassis holes; supports brackets and mounts.','Болты через совмещённые отверстия; сюда крепятся уголки и держатели.','Mos shassi teshiklari orqali boltlanadi; burchak va tutqichlarni ushlaydi.'];
const mount=['Bolts to a chassis hole or raised fitting. Wires reach Arduino separately.','Крепится к отверстию шасси или стойки. Провода отдельно идут к Arduino.','Shassi yoki ko‘tarilgan tayanch teshigiga mahkamlanadi. Simlar Arduino ga alohida ulanadi.'];
const analog=['VCC → 5V; GND → GND1; OUT → A0 (14). Give each extra sensor its own input.','VCC → 5V; GND → GND1; OUT → A0 (14). Каждому следующему датчику — свой вход.','VCC → 5V; GND → GND1; OUT → A0 (14). Qo‘shimcha sensorlarga alohida kirish bering.'];
// name, purpose, connection, pins, common mistake, independent extension.
const parts={
 board:[['Arduino Uno','Arduino Uno','Arduino Uno'],['The brain: reads sensors and commands LEDs and motors.','Мозг: читает датчики, управляет LED и моторами.','Miya: sensorlarni o‘qiydi, LED va motorlarni boshqaradi.'],['Bolts to the frame. Header pins accept Dupont leads; modules stay off the board.','Крепится к раме. К контактам подключаются провода Dupont; модули находятся отдельно.','Ramaga boltlanadi. Header pinlariga Dupont simlari ulanadi; modullar platadan tashqarida turadi.'],['D0–D13: digital; A0–A5: analog (14–19); 5V: supply; GND: ground.','D0–D13: цифровые; A0–A5: аналоговые (14–19); 5V: питание; GND: земля.','D0–D13: raqamli; A0–A5: analog (14–19); 5V: quvvat; GND: umumiy nuqta.'],['A bolt holds the board; it does not wire a sensor.','Болт держит плату, но не подключает датчик.','Bolt platani ushlaydi, sensorni elektrga ulamaydi.'],['Trace 5V and its GND return.','Проследи 5V и обратный путь GND.','5V va GND qaytish yo‘lini kuzating.']],
 deck:[['Deck plate','Платформа','Platforma'],['A broad platform for a stable body.','Широкая основа устойчивого корпуса.','Barqaror tana uchun keng platforma.'],hole,null,['One bolt pivots; two between the same parts lock the joint.','Один болт — шарнир; два между теми же деталями закрепляют стык.','Bitta bolt buriladi; bir xil detallar orasidagi ikkita bolt birikmani qotiradi.'],['Bolt two overlapping holes to a strip.','Соедини с планкой через два совпавших отверстия.','Plankaga ikkita mos teshik orqali boltlang.']],
 lbracket:[['L-bracket','Уголок','Burchak'],['Turns a connection through a right angle.','Поворачивает крепление на прямой угол.','Mahkamlashni to‘g‘ri burchakka buradi.'],mount,null,['Orient the next plate to match the raised hole’s plane.','Поверни пластину в плоскость поднятого отверстия.','Keyingi plastinani yuqori teshik tekisligiga burang.'],['Make a shelf above the frame.','Сделай полку над рамой.','Rama ustida tokcha quring.']],
 standoff:[['Standoff','Стойка','Ustuncha'],['Raises a mounting hole above another part.','Поднимает крепление над другой деталью.','Mahkamlashni boshqa detal ustiga ko‘taradi.'],mount,null,['The child snaps to the raised hole, not the base.','Деталь крепится к верхнему отверстию, не к основанию.','Detal tagiga emas, yuqori teshikka ulanadi.'],['Lift a sensor above the deck.','Подними датчик над платформой.','Sensorni platforma ustiga ko‘taring.']],
 upright:[['Upright post','Вертикальная планка','Tik tayanch'],['Offers holes at several heights.','Даёт отверстия на разной высоте.','Turli balandlikda teshiklar beradi.'],mount,null,['Aim at the exact height; the holes share a ground position.','Целься в нужную высоту: отверстия друг над другом.','Aniq balandlikni nishonga oling: teshiklar ustma-ust.'],['Mount a sensor low, then high.','Установи датчик ниже, затем выше.','Sensorni pastga, keyin balandga qo‘ying.']],
 motormount:[['Motor mount','Держатель мотора','Motor tutqichi'],['Holds a motor and points its axle.','Держит мотор и направляет его ось.','Motorni ushlab, o‘qini yo‘naltiradi.'],['Chassis hole → mount → motor seat.','Отверстие шасси → держатель → мотор.','Shassi teshigi → tutqich → motor.'],null,['A wheel needs a motor shaft, not this empty cradle.','Колесу нужен вал мотора, не пустой держатель.','G‘ildirakka bo‘sh tutqich emas, motor vali kerak.'],['Make left and right motor cradles.','Сделай левое и правое крепления.','Chap va o‘ng tutqichlarni tayyorlang.']],
 motor:[['DC motor','Мотор постоянного тока','Doimiy tok motori'],['Turns commands into wheel motion.','Превращает команды во вращение.','Buyruqlarni g‘ildirak harakatiga aylantiradi.'],['Motor mount → motor → wheel. Both motor leads go to one L293D output pair.','Держатель → мотор → колесо. Оба провода мотора идут к паре выходов L293D.','Tutqich → motor → g‘ildirak. Ikkala motor simi bitta L293D chiqish juftiga ulanadi.'],['M+ and M− → OUT1/OUT2; IN1/IN2 set direction; EN, logic 5V, 9V motor power and common GND are required.','M+ и M− → OUT1/OUT2; IN1/IN2 задают направление; нужны EN, 5V логики, 9V мотора и общая GND.','M+ va M− → OUT1/OUT2; IN1/IN2 yo‘nalishni beradi; EN, 5V logika, 9V motor quvvati va umumiy GND kerak.'],['One motor wire or direct Uno power is an incomplete circuit.','Один провод или прямое питание от Uno — неполная схема.','Bitta motor simi yoki Uno dan bevosita quvvat — noto‘liq sxema.'],['Remove one lead and confirm that Run reports the missing circuit.','Убери один провод и проверь сообщение о неполной цепи.','Bitta simni uzib, Run noto‘liq sxemani ko‘rsatishini tekshiring.']],
 wheel:[['Wheel','Колесо','G‘ildirak'],['Pushes against the ground to move the robot.','Отталкивается от земли и двигает робота.','Yerga tayanib robotni yurgizadi.'],['Only a motor shaft. Position follows the mount chain.','Только вал мотора. Положение задаёт цепочка креплений.','Faqat motor vali. Joyi mahkamlash zanjiriga bog‘liq.'],null,['A wheel has no pin: control its parent motor.','У колеса нет контакта: управляй его мотором.','G‘ildirakda pin yo‘q: uning motorini boshqaring.'],['Build hole → mount → motor → wheel.','Собери отверстие → держатель → мотор → колесо.','Teshik → tutqich → motor → g‘ildirak yig‘ing.']],
 caster:[['Ball caster','Шаровая опора','Sharli tayanch'],['Supports the other end while the rover turns.','Поддерживает второй конец при повороте.','Burilishda roverning boshqa uchini ushlaydi.'],['A free chassis hole; no motor needed.','Свободное отверстие шасси; мотор не нужен.','Bo‘sh shassi teshigi; motor kerak emas.'],null,['It supports weight; it cannot drive.','Держит вес, но не приводит в движение.','Og‘irlikni ushlaydi, yurgizmaydi.'],['Add support opposite the powered wheels.','Добавь опору напротив ведущих колёс.','Yetakchi g‘ildiraklar qarshisiga tayanch qo‘shing.']],
 led:[['Red LED','Красный LED','Qizil LED'],['Makes HIGH and LOW visible.','Показывает HIGH и LOW светом.','HIGH va LOW ni yorug‘likda ko‘rsatadi.'],['Mounts on the chassis; its anode reaches Arduino through a resistor.','Крепится к шасси; анод идёт к Arduino через резистор.','Shassiga mahkamlanadi; anod Arduino ga rezistor orqali boradi.'],['D13 → 220 Ω resistor → A; K → GND. HIGH: on; LOW: off.','D13 → резистор 220 Ом → A; K → GND. HIGH: вкл.; LOW: выкл.','D13 → 220 Ω rezistor → A; K → GND. HIGH: yoniq; LOW: o‘chiq.'],['Without the resistor the simulator rejects the unsafe circuit.','Без резистора симулятор отклоняет опасную схему.','Rezistorsiz xavfli sxemani simulyator qabul qilmaydi.'],['Alternate HIGH, wait 500 ms, LOW, wait 500 ms.','Чередуй HIGH, паузу 500 мс, LOW, паузу 500 мс.','HIGH, 500 ms kutish, LOW, 500 ms kutishni takrorlang.']],
 sensor:[['Ultrasonic sensor','Ультразвуковой датчик','Ultratovush sensori'],['Times an echo to measure obstacle distance in cm.','Измеряет время эха и расстояние до препятствия в см.','Aks-sado vaqtini o‘lchab, to‘siq masofasini cm da topadi.'],mount,['VCC → 5V; GND → GND1; TRIG → D6; ECHO → D7.','VCC → 5V; GND → GND1; TRIG → D6; ECHO → D7.','VCC → 5V; GND → GND1; TRIG → D6; ECHO → D7.'],['A signal wire alone cannot power it. TRIG and ECHO have different jobs.','Один сигнал не питает датчик. У TRIG и ECHO разные задачи.','Signal simining o‘zi quvvat bermaydi. TRIG va ECHO vazifalari boshqa.'],['Point the round faces at a wall; compare near and far.','Направь круглые излучатели на стену; сравни близко и далеко.','Dumaloq yuzlarni devorga qaratib, yaqin va uzoqni solishtiring.']],
};
const sensorRows={
 lineSensor:[['Line sensor','Датчик линии','Chiziq sensori'],['Reads the surface under the robot to detect a line.','Читает поверхность под роботом и замечает линию.','Robot ostidagi yuzani o‘qib, chiziqni topadi.'],['It looks down. Distance is not a line reading.','Смотрит вниз. Расстояние — не показание линии.','Pastga qaraydi. Masofa chiziq o‘lchovi emas.'],['Compare OUT on the line and beside it.','Сравни OUT на линии и рядом.','Chiziq usti va yonidagi OUT ni solishtiring.']],
 lightSensor:[['Light sensor','Датчик света','Yorug‘lik sensori'],['Measures ambient light in the lab.','Измеряет свет в лаборатории.','Laboratoriya yorug‘ligini o‘lchaydi.'],['Reads the lab environment, not your monitor brightness.','Читает среду, не яркость монитора.','Muhitni o‘qiydi, monitor yorqinligini emas.'],['Change Light in the sensor lab.','Измени свет в лаборатории.','Laboratoriyada yorug‘likni o‘zgartiring.']],
 temperatureSensor:[['Temperature sensor','Датчик температуры','Harorat sensori'],['Measures lab temperature in °C.','Измеряет температуру среды в °C.','Muhit haroratini °C da o‘lchaydi.'],['Unwired is not a valid zero-degree reading.','Нет подключения — не значит ноль градусов.','Ulanmagan sensor nol darajali o‘lchov emas.'],['Predict the result, then change Temperature in the lab.','Предскажи результат и измени температуру в лаборатории.','Natijani taxmin qilib, laboratoriya haroratini o‘zgartiring.']],
 touchSensor:[['Touch sensor','Датчик касания','Tegish sensori'],['Reports contact with an obstacle.','Сообщает о касании препятствия.','To‘siqqa tegishni bildiradi.'],['Nearby is not touching.','Близко — ещё не касание.','Yaqin turish tegish emas.'],['Approach an obstacle slowly and watch OUT.','Медленно приблизься к препятствию и следи за OUT.','To‘siqqa sekin yaqinlashib, OUT ni kuzating.']],
 tiltSensor:[['Tilt sensor','Датчик наклона','Qiyalik sensori'],['Reports the robot’s inclination.','Показывает наклон робота.','Robot qiyaligini ko‘rsatadi.'],['Turning on level ground differs from tilting.','Поворот на ровном полу — не наклон.','Tekis yerda burilish qiyshayish emas.'],['Compare level ground and a ramp.','Сравни ровную землю и пандус.','Tekis yer va qiyalikni solishtiring.']],
 encoderSensor:[['Encoder sensor','Энкодер','Enkoder sensori'],['Reports accumulated movement.','Показывает накопленное движение.','Jamlangan harakatni ko‘rsatadi.'],['A speed command alone does not prove movement.','Команда скорости ещё не доказывает движение.','Tezlik buyrug‘i harakat isboti emas.'],['Compare short and long drives at equal speed.','Сравни короткую и длинную поездки на одной скорости.','Teng tezlikdagi qisqa va uzun yurishni solishtiring.']],
};
for (const [kind,[name,purpose,mistake,experiment]] of Object.entries(sensorRows)) parts[kind]=[name,purpose,mount,analog,mistake,experiment];
for (const kind of Object.keys(KIT_COPY.en.parts)) if (!parts[kind]) parts[kind]=[
  [KIT_COPY.en.parts[kind].name,KIT_COPY.ru.parts[kind].name,KIT_COPY.uz.parts[kind].name],
  [KIT_COPY.en.parts[kind].desc,KIT_COPY.ru.parts[kind].desc,KIT_COPY.uz.parts[kind].desc],
  mount,
  ['Use the labelled terminals; power, ground and signal roles are checked.','Используй подписанные контакты: питание, земля и сигнал проверяются.','Belgilangan terminallardan foydalaning; quvvat, GND va signal tekshiriladi.'],
  ['An incomplete or reversed circuit stays inactive.','Неполная или обратная цепь остаётся неактивной.','To‘liq bo‘lmagan yoki teskari zanjir ishlamaydi.'],
  ['Wire it, remove one required lead, and compare the result.','Подключи, убери один обязательный провод и сравни результат.','Ulang, bitta zarur simni uzib, natijani solishtiring.'],
];
for (const n of [5,7,11,15]) parts['strip'+n]=[
 [n+'-hole strip','Планка: '+n+' отверстий',n+' teshikli planka'],
 ['A light beam for rails and overlapping joints.','Лёгкая балка для рамы и соединений внахлёст.','Rama va ustma-ust birikmalar uchun yengil balka.'],hole,null,
 ['Align hole centres and plate planes before bolting.','Совмести центры отверстий и плоскости пластин.','Teshik markazlari va plastina tekisliklarini moslang.'],
 ['Overlap two strips at two holes. Compare one bolt with two.','Наложи две планки двумя отверстиями. Сравни один болт и два.','Ikki plankani ikki teshikda ustma-ust qo‘ying. Bir va ikki boltni solishtiring.']];
const mechanicalRows={
 plate3x5:[['3×5 perforated plate','Перфорированная пластина 3×5','3×5 teshikli plastina'],['A compact rigid face for bases, towers and shoulders.','Жёсткая площадка для основания, башни или плеча.','Asos, minora va yelka uchun qattiq yuza.'],['Two separated bolts prevent the plate from pivoting.','Два разнесённых болта не дают пластине вращаться.','Bir-biridan uzoq ikki bolt plastinani burilishdan saqlaydi.'],['Stand it upright with two L-brackets.','Поставь вертикально на двух уголках.','Ikki L-burchak yordamida tik o‘rnating.']],
 turntableBase:[['Turntable base','Основание поворотного круга','Aylanuvchi asos'],['The fixed lower race of a rotating robot base.','Неподвижная нижняя часть поворотного основания.','Robot aylanuvchi asosining qotirilgan pastki qismi.'],['Fix its outer holes; leave the centre for the rotating top.','Закрепи внешние отверстия, оставь центр верхнему диску.','Tashqi teshiklarni qotiring, markazni yuqori disk uchun qoldiring.'],['Bolt it to a wide deck at two outer holes.','Закрепи на платформе двумя внешними болтами.','Keng platformaga ikki tashqi bolt bilan ulang.']],
 turntableTop:[['Turntable top','Верх поворотного круга','Aylanuvchi ustki disk'],['Carries the arm while one centre bolt forms a yaw joint.','Несёт руку; один центральный болт образует поворотный шарнир.','Qo‘lni ko‘taradi; bitta markaziy bolt aylanish sharnirini hosil qiladi.'],['Adding a second bolt to the base locks the rotation.','Второй болт к основанию блокирует вращение.','Asosga ikkinchi bolt aylanishni qotirib qo‘yadi.'],['Put brackets on opposite outer holes for a tower.','Поставь уголки в противоположные внешние отверстия.','Minora uchun qarama-qarshi tashqi teshiklarga burchak qo‘ying.']],
 gearSmall:[['Small gear','Малая шестерня','Kichik tishli g‘ildirak'],['A compact pinion for visible rotational mechanisms.','Малая ведущая шестерня механизма.','Ko‘rinadigan aylanish mexanizmi uchun kichik tishli g‘ildirak.'],['One centre bolt is the axle; two bolts lock it.','Один центральный болт — ось, два болта блокируют.','Bitta markaziy bolt — o‘q; ikkitasi uni qotiradi.'],['Build a free-spinning gear pair on a plate.','Собери свободно вращающуюся пару на пластине.','Plastinada erkin aylanadigan tishli juftlik quring.']],
 gearLarge:[['Large gear','Большая шестерня','Katta tishli g‘ildirak'],['A larger wheel for torque and visible reduction.','Большое колесо для момента и наглядной передачи.','Kuch momenti va ko‘rinadigan uzatma uchun katta g‘ildirak.'],['Use only the centre bolt if it must rotate.','Если шестерня должна вращаться, используй только центральный болт.','Aylanishi kerak bo‘lsa, faqat markaziy boltni ishlating.'],['Compare its rotation with the small pinion.','Сравни вращение с малой шестерней.','Aylanishini kichik tishli bilan solishtiring.']],
 gripperPalm:[['Gripper palm','Ладонь захвата','Qisqich kafti'],['A five-hole wrist plate for two jaws and two servos.','Пятипозиционная кисть для двух губок и сервоприводов.','Ikki jag‘ va servolar uchun besh teshikli bilak plastinasi.'],['Keep the centre for the wrist and outer holes for jaw pivots.','Оставь центр для кисти, крайние отверстия — для губок.','Markazni bilak, chet teshiklarni jag‘ sharnirlari uchun qoldiring.'],['Attach each jaw with exactly one bolt.','Закрепи каждую губку ровно одним болтом.','Har bir jag‘ni aynan bitta bolt bilan ulang.']],
 gripperJawL:[['Left gripper jaw','Левая губка','Chap qisqich jag‘i'],['The hooked left finger of a working claw.','Левый крюк рабочего захвата.','Ishlaydigan qisqichning chap ilgak barmog‘i.'],['Two bolts stop the jaw from closing.','Два болта не дадут губке закрываться.','Ikki bolt jag‘ning yopilishiga yo‘l qo‘ymaydi.'],['Drive its one-bolt hinge with a nearby servo.','Приведи одноболтовый шарнир ближайшим сервоприводом.','Bitta boltli sharnirni yaqin servo bilan boshqaring.']],
 gripperJawR:[['Right gripper jaw','Правая губка','O‘ng qisqich jag‘i'],['The mirrored right finger of a working claw.','Зеркальная правая губка рабочего захвата.','Ishlaydigan qisqichning ko‘zgudek o‘ng jag‘i.'],['Mount it opposite the left jaw, not on the same hole.','Установи напротив левой губки, не в то же отверстие.','Chap jag‘ qarshisiga, boshqa teshikka o‘rnating.'],['Command opposite servo angles to close both fingers.','Задай противоположные углы двух сервоприводов.','Ikki servoga qarama-qarshi burchak berib qisqichni yoping.']],
};
for(const [kind,[name,purpose,mistake,experiment]] of Object.entries(mechanicalRows)) parts[kind]=[name,purpose,hole,null,mistake,experiment];
const names={
 basics:[['01 · Frame & space','01 · Рама и пространство','01 · Rama va fazo'],['Join, bolt, explore XYZ.','Соедини, закрепи, исследуй XYZ.','Ulang, boltlang, XYZ ni o‘rganing.']],
 led:[['02 · A little light','02 · Маленький огонёк','02 · Kichik chiroq'],['Make a real pin blink.','Заставь контакт мигать.','Haqiqiy pinni miltillating.']],
 rover:[['03 · Wheels that work','03 · Колёса в деле','03 · Ishlaydigan g‘ildiraklar'],['Build a drivetrain and prove motion.','Собери привод и докажи движение.','Yuritma yig‘ib, harakatni isbotlang.']],
 ultrasonic:[['04 · Hear the distance','04 · Услышать расстояние','04 · Masofani eshiting'],['Four leads turn an echo into a decision.','Четыре провода превращают эхо в решение.','To‘rtta sim aks-sadoni qarorga aylantiradi.']],
 line:[['05 · Follow a line','05 · По следу линии','05 · Chiziqni kuzating'],['Sense, steer, repeat.','Измеряй, рули, повторяй.','Sezing, boshqaring, takrorlang.']],
};
// title, action, why, common mistake, try yourself.
const steps={
 frame:[['Make a frame','Собери раму','Rama yig‘ing'],['Place two metal strips. Overlap two holes for the next step.','Размести две планки. Совмести два отверстия для следующего шага.','Ikki planka qo‘ying. Keyingi qadam uchun ikki teshikni ustma-ust qo‘ying.'],['A frame gives every part a shared structure.','Рама объединяет детали.','Rama barcha detallarni birlashtiradi.'],['One board does not replace two strips.','Одна плата не заменяет две планки.','Bitta plata ikki plankani almashtirmaydi.'],['Try a short strip across a long one.','Положи короткую планку поперёк длинной.','Qisqa plankani uzuniga ko‘ndalang qo‘ying.']],
 bolts:[['Lock the joint','Закрепи стык','Birikmani qotiring'],['Join the same two strips with at least two bolts.','Соедини те же две планки минимум двумя болтами.','Bir xil ikki plankani kamida ikki bolt bilan ulang.'],['One bolt pivots; two between these parts make a rigid joint.','Один болт — шарнир; два между этими деталями делают стык жёстким.','Bitta bolt buriladi; shu detallar orasidagi ikkita bolt birikmani qotiradi.'],['Bolts on unrelated joints do not count.','Болты в разных стыках не считаются.','Boshqa birikmadagi boltlar hisoblanmaydi.'],['Undo one bolt and read the coach’s explanation.','Отмени один болт и прочитай объяснение.','Bitta boltni bekor qilib, izohni o‘qing.']],
 xyz:[['Explore three axes','Исследуй три оси','Uch o‘qni o‘rganing'],['Select one strip. Move that same strip on X, Y and Z: arrows on the floor, PageUp/PageDown for height. R/T/F rotate about Y/X/Z.','Выбери планку. Перемести её по X, Y и Z: стрелки — по полу; PageUp/PageDown — высота. R/T/F — вращение Y/X/Z.','Bir plankani tanlang. Uni X, Y, Z bo‘ylab suring: strelkalar — yerda, PageUp/PageDown — balandlik. R/T/F — Y/X/Z atrofida burish.'],['Position has three independent coordinates.','У положения три независимые координаты.','Joylashuv uch mustaqil koordinataga ega.'],['Moving the camera does not move a part. Click the scene before shortcuts.','Камера не перемещает деталь. Перед клавишами нажми на сцену.','Kamera detalni surmaydi. Tugmalardan oldin sahnani bosing.'],['Undo the moves; try a vertical plate with T.','Отмени движения; поверни пластину вертикально клавишей T.','Surishlarni bekor qilib, T bilan plastinani tik burang.']],
 ledSeat:[['Wire an external LED safely','Безопасно подключи внешний LED','Tashqi LED ni xavfsiz ulang'],['Mount the LED away from Arduino. Wire D13 → 220 Ω resistor → A and K → GND.','Закрепи LED отдельно. Соедини D13 → резистор 220 Ом → A и K → GND.','LED ni alohida mahkamlang. D13 → 220 Ω rezistor → A va K → GND ulang.'],['The resistor limits current; GND completes the path.','Резистор ограничивает ток, а GND замыкает путь.','Rezistor tokni cheklaydi, GND esa yo‘lni yakunlaydi.'],['Direct D13 → A is rejected as unsafe.','Прямое D13 → A отклоняется как опасное.','Bevosita D13 → A xavfli deb rad etiladi.'],['Trace all three leads before running the code.','Проверь все три провода перед запуском.','Kodni ishga tushirishdan oldin uchala simni kuzating.']],
 blinkCode:[['Write the rhythm','Задай ритм','Ritmni yozing'],['Repeat forever: pin 13 HIGH → wait 500 ms → pin 13 LOW → wait 500 ms.','Повторять всегда: 13 HIGH → ждать 500 мс → 13 LOW → ждать 500 мс.','Doim takrorlash: 13 HIGH → 500 ms kutish → 13 LOW → 500 ms kutish.'],['Both waits make each state visible.','Обе паузы делают состояния видимыми.','Ikkala kutish holatlarni ko‘rishga yordam beradi.'],['Writes without waits can look like constant light.','Записи без пауз выглядят как постоянный свет.','Kutishsiz yozuvlar doimiy chiroqdek ko‘rinadi.'],['Predict the effect of 1000 ms waits.','Предскажи эффект пауз по 1000 мс.','1000 ms kutish ta’sirini taxmin qiling.']],
 blinkRun:[['See HIGH and LOW','Увидь HIGH и LOW','HIGH va LOW ni ko‘ring'],['Start a fresh Run. Wait for this D13 LED to turn on and off.','Начни новый запуск. Дождись включения и выключения LED D13.','Yangidan ishga tushiring. Shu D13 LED yonib-o‘chishini kuting.'],['The guide checks this LED’s actual output.','Помощник проверяет реальный выход этого LED.','Qo‘llanma shu LED ning haqiqiy chiqishini tekshiradi.'],['After editing, stop the old run and start again.','После правки останови старый запуск и начни новый.','Tahrirdan keyin eski yurishni to‘xtatib, qayta boshlang.'],['Make on-time longer than off-time.','Сделай включение длиннее выключения.','Yoniq vaqtni o‘chiq vaqtdan uzaytiring.']],
 drivetrain:[['Build both drive chains','Собери оба привода','Ikkala yuritmani yig‘ing'],['Build two chains and connect both motors through the two L293D channels; add a caster.','Собери две цепочки и подключи моторы через два канала L293D; добавь шаровую опору.','Ikki yuritma zanjirini yig‘ing, motorlarni L293D ning ikki kanaliga ulang va sharli tayanch qo‘shing.'],['The shaft locates the wheel; the powered bridge controls direction and braking.','Вал задаёт место колеса; запитанный мост управляет направлением и торможением.','Val g‘ildirak joyini belgilaydi; quvvatlangan ko‘prik yo‘nalish va tormozni boshqaradi.'],['A missing M−, enable, ground or battery lead keeps that motor off.','Без M−, EN, земли или батареи мотор не включится.','M−, EN, GND yoki batareya simi yetishmasa motor ishlamaydi.'],['Select each motor and inspect both electrical terminals.','Выбери каждый мотор и проверь оба электрических контакта.','Har bir motorni tanlab, ikkala elektr terminalini tekshiring.']],
 driveCode:[['Command a real movement','Задай реальное движение','Haqiqiy harakat buyrug‘ini bering'],['Drive forward at speed 140 for at least 1500 ms. An optional Wait may come first.','Ехать вперёд со скоростью 140 минимум 1500 мс. Перед этим можно добавить ожидание.','140 tezlikda kamida 1500 ms oldinga yuring. Oldiga ixtiyoriy Kutish bloki qo‘shish mumkin.'],['The simulator settles the physics before starting your first block.','Симулятор стабилизирует физику до первого блока.','Simulyator birinchi blokdan oldin fizikani barqarorlashtiradi.'],['Say prints words; it does not move wheels.','«Сказать» печатает, но не двигает колёса.','Aytish so‘z chiqaradi, g‘ildirakni yurgizmaydi.'],['After testing, change forward to left.','После проверки замени «вперёд» на «влево».','Tekshiruvdan so‘ng oldinga o‘rniga chapga tanlang.']],
 driveRun:[['Prove it moved','Докажи движение','Harakatni isbotlang'],['Start a fresh Run. Move with both powered wheels by at least half a grid pitch.','Начни новый запуск. Сдвинься обоими ведущими колёсами хотя бы на половину шага сетки.','Yangidan ishga tushiring. Ikki yetakchi g‘ildirakda kamida yarim to‘r qadamiga suriling.'],['Wheel motion and ground travel prove the drivetrain works.','Вращение и путь по земле подтверждают работу привода.','G‘ildirak harakati va yerdagi yo‘l yuritma ishini isbotlaydi.'],['Falling or an idle Run is not travel.','Падение или пустой запуск — не езда.','Tushish yoki bo‘sh Run yurish emas.'],['Try the route at half speed.','Пройди путь на половине скорости.','Yo‘lni yarim tezlikda sinang.']],
 sonarWire:[['Four leads, four jobs','Четыре провода — четыре задачи','To‘rtta sim — to‘rtta vazifa'],['Mount ultrasonic. On one Uno: VCC → 5V, GND → GND1, TRIG → D6, ECHO → D7. Add LED D13.','Закрепи датчик. На одной Uno: VCC → 5V, GND → GND1, TRIG → D6, ECHO → D7. Добавь LED D13.','Sensorni mahkamlang. Bitta Uno: VCC → 5V, GND → GND1, TRIG → D6, ECHO → D7. LED D13 qo‘shing.'],['TRIG starts sound; ECHO returns timing.','TRIG запускает звук; ECHO возвращает время.','TRIG tovush boshlaydi; ECHO vaqtni qaytaradi.'],['Reversing TRIG and ECHO does not match this plan.','Перестановка TRIG и ECHO не соответствует схеме.','TRIG va ECHO ni almashtirish rejaga mos emas.'],['Tap each route to see both ends.','Нажми на каждый провод и найди концы.','Har bir yo‘lni bosib, uchlarini toping.']],
 sonarCode:[['Turn a reading into a choice','Преврати показание в выбор','O‘lchovni tanlovga aylantiring'],['Repeat forever: If distance < 20 cm → pin 13 HIGH; else → pin 13 LOW. Then wait 100 ms.','Повторять всегда: если расстояние < 20 см → 13 HIGH; иначе → 13 LOW. Затем ждать 100 мс.','Doim takrorlash: masofa < 20 cm → 13 HIGH; aks holda → 13 LOW. So‘ng 100 ms kutish.'],['A threshold converts a measurement into a decision.','Порог превращает измерение в решение.','Chegara o‘lchovni qarorga aylantiradi.'],['LOW belongs in else, not after the whole condition.','LOW нужен в «иначе», не после всего условия.','LOW butun shartdan keyin emas, aks holda ichida bo‘lsin.'],['Predict the branch at 30 cm.','Предскажи ветку при 30 см.','30 cm dagi tarmoqni taxmin qiling.']],
 sonarRun:[['Read, decide, light','Измерь, реши, зажги','O‘lchang, tanlang, yoqing'],['Start a fresh Run. Wait for a ready sensor reading and its matching D13 output.','Начни новый запуск. Дождись готового показания и соответствующего выхода D13.','Yangidan ishga tushiring. Tayyor o‘lchov va mos D13 chiqishini kuting.'],['Output must agree with the measured 20 cm rule.','Выход должен совпадать с правилом 20 см.','Chiqish o‘lchangan 20 cm qoidasiga mos bo‘lsin.'],['An unpowered zero is not proof of an obstacle.','Ноль без питания не доказывает препятствие.','Quvvatsiz nol to‘siq isboti emas.'],['Move closer and run again to test the other branch.','Приблизься и запусти снова для другой ветки.','Yaqinlashib, boshqa tarmoq uchun qayta boshlang.']],
 lineWire:[['Look at the ground','Посмотри на землю','Yerga qarang'],['Add line sensor to a two-wheel rover: VCC → 5V, GND → GND1, OUT → A0. Choose the line-following arena.','На двухколёсном ровере: VCC → 5V, GND → GND1, OUT → A0 датчика линии. Выбери арену с линией.','Ikki g‘ildirakli roverda: chiziq sensori VCC → 5V, GND → GND1, OUT → A0. Chiziqli maydonni tanlang.'],['The surface reading can guide steering.','Показание поверхности помогает рулить.','Yuza o‘lchovi boshqarishga yordam beradi.'],['Ultrasonic cannot replace a line sensor.','Ультразвук не заменяет датчик линии.','Ultratovush chiziq sensorini almashtirmaydi.'],['Compare OUT on dark and light ground in the lab.','Сравни OUT на тёмном и светлом в лаборатории.','Laboratoriyada qora va yorug‘ yuzadagi OUT ni solishtiring.']],
 lineCode:[['Sense, then steer','Измеряй и рули','Sezing, so‘ng boshqaring'],['Repeat forever: If Sensor A0 < a threshold between 0 and 100, Drive left; else Drive right. Moves: 100–400 ms, speed above 0. An initial Wait is optional.','Повторять всегда: если датчик A0 < порога между 0 и 100, ехать влево; иначе вправо. Движения 100–400 мс, скорость > 0. Начальное ожидание необязательно.','Doim takrorlash: Sensor A0 < 0 va 100 orasidagi chegara bo‘lsa, chapga; aks holda o‘ngga. Harakat 100–400 ms, tezlik > 0. Boshlang‘ich Kutish ixtiyoriy.'],['Short corrections let the robot sample the surface again.','Короткие поправки дают снова измерить поверхность.','Qisqa tuzatishlar yuzani qayta o‘lchashga vaqt beradi.'],['A timed loop without a sensor condition is not feedback.','Цикл по таймеру без датчика — не обратная связь.','Sensor shartisiz vaqtli sikl qayta aloqa emas.'],['Predict how longer turns change the zigzag.','Предскажи зигзаг с длинными поворотами.','Uzunroq burilish zigzagini taxmin qiling.']],
 lineRun:[['Try a feedback loop','Испытай обратную связь','Qayta aloqani sinang'],['Start a fresh Run. Observe two different line readings while matching steering moves both wheels.','Начни новый запуск. Наблюдай два разных показания линии при соответствующем движении обоих колёс.','Yangidan ishga tushiring. Ikki g‘ildirak mos burilganda ikki turli chiziq o‘lchovini kuzating.'],['Changing readings and matching motion prove the loop is connected.','Изменение показаний и верное движение подтверждают связь.','O‘zgaruvchi o‘lchov va mos harakat sikl ulanganini isbotlaydi.'],['Run or a different mission victory alone does not pass.','Запуск или победа в другой миссии не засчитываются.','Faqat Run yoki boshqa vazifadagi g‘alaba hisoblanmaydi.'],['Tune speed and threshold to stay on the track longer.','Подстрой скорость и порог, чтобы дольше держаться линии.','Chiziqda uzoqroq qolish uchun tezlik va chegarani sozlang.']],
};
export const workshopCopy=Object.fromEntries(['en','ru','uz'].map((locale,i)=>[locale,{
 ...Object.fromEntries(Object.entries(ui).map(([k,v])=>[k,v[i]])),
 parts:Object.fromEntries(Object.entries(parts).map(([k,v])=>[k,Object.fromEntries(['name','purpose','connects','pins','mistake','try'].map((f,n)=>[f,v[n]?.[i]??ui.noPins[i]]))])),
 lesson:Object.fromEntries(Object.entries(names).map(([k,v])=>[k,{title:v[0][i],summary:v[1][i]}])),
 steps:Object.fromEntries(Object.entries(steps).map(([k,v])=>[k,Object.fromEntries(['title','action','why','mistake','try'].map((f,n)=>[f,v[n][i]]))])),
}]));
export const getWorkshopCopy=locale=>workshopCopy[locale]??workshopCopy.en;

