/**
 * The text-code layer: emitter, parser, round trip, and the extended blocks.
 *
 *   node tools/code-test.mjs
 *
 * Pure node, no browser and no build — program.js and arduinoParser.js have no
 * React and no DOM in them, which is the whole reason they are separate from
 * the editor that draws them (same argument as tools/model-test.mjs).
 *
 * The property that matters most is the ROUND TRIP: blocks -> C++ -> blocks has
 * to come back unchanged. If it does not, a student who opens the code tab and
 * switches back has silently had their program rewritten.
 */
import {
  BLOCK_TYPES,
  collectVars,
  duplicateBlock,
  findBlock,
  makeBlock,
  makeRunner,
  moveBlock,
  num,
  safeVarName,
  toArduinoCode,
  variable,
} from '../src/lib/program.js'
import { parseArduino } from '../src/lib/arduinoParser.js'

const results = []
const check = (name, ok, detail = '') =>
  results.push(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? '  — ' + detail : ''}`)

/** Structural equality ignoring the ids, which are regenerated by design. */
const strip = (b) => {
  if (Array.isArray(b)) return b.map(strip)
  if (b && typeof b === 'object') {
    const out = {}
    for (const k of Object.keys(b).sort()) {
      if (k === 'id') continue
      out[k] = strip(b[k])
    }
    return out
  }
  return b
}
const same = (a, b) => JSON.stringify(strip(a)) === JSON.stringify(strip(b))

const roundTrip = (blocks) => {
  const code = toArduinoCode(blocks, {})
  const parsed = parseArduino(code)
  return { code, parsed }
}

/* ------------------------------------------------- every block, one by one */

for (const type of Object.keys(BLOCK_TYPES)) {
  const block = makeBlock(type)
  // Containers need something inside them to be worth checking.
  if (block.body) block.body = [makeBlock('wait')]
  if (block.elseBody) block.elseBody = [makeBlock('print')]

  const { code, parsed } = roundTrip([block])
  const ok = !parsed.error && same(parsed.blocks, [block])
  check(
    `Round trip: ${type}`,
    ok,
    parsed.error ? `${parsed.error.message} (line ${parsed.error.line})` : ok ? '' : JSON.stringify(parsed.blocks),
  )
}

/* --------------------------------------------------- a whole small program */

const program = [
  { ...makeBlock('setVar'), name: 'count', a: num(0), op: '', b: num(1) },
  {
    ...makeBlock('forever'),
    body: [
      {
        ...makeBlock('ifDistance'),
        op: '<',
        cm: 25,
        body: [{ ...makeBlock('drive'), dir: 'back', speed: 180, ms: 800 }],
        elseBody: [{ ...makeBlock('drive'), dir: 'forward', speed: 220, ms: 1200 }],
      },
      { ...makeBlock('setVar'), name: 'count', a: variable('count'), op: '+', b: num(1) },
      {
        ...makeBlock('ifCompare'),
        a: variable('count'),
        op: '>=',
        b: num(5),
        body: [{ ...makeBlock('print'), text: 'five laps' }],
        elseBody: [],
      },
    ],
  },
]

const whole = roundTrip(program)
check(
  'Round trip: a whole nested program',
  !whole.parsed.error && same(whole.parsed.blocks, program),
  whole.parsed.error
    ? `${whole.parsed.error.message} (line ${whole.parsed.error.line})`
    : same(whole.parsed.blocks, program)
      ? ''
      : 'structure changed',
)
check(
  'Variables are declared as globals above setup()',
  whole.code.includes('int count = 0;') &&
    whole.code.indexOf('int count = 0;') < whole.code.indexOf('void setup()'),
  whole.code.split('\n').slice(0, 4).join(' | '),
)
check('collectVars finds the variable', JSON.stringify(collectVars(program)) === '["count"]', JSON.stringify(collectVars(program)))

/* ------------------------------------------- hand-written code, not emitted */

const handWritten = `
void setup() { Serial.begin(9600); }

void loop() {
  int hits = 0;
  while (readDistanceCm() > 30) {
    setMotor(9, 200);
    hits++;
  }
  setMotor(9, 0);
  if (hits >= 3) {
    Serial.println("plenty");
  } else {
    Serial.println("few");
  }
  for (int i = 0; i < 3; i++) {
    digitalWrite(13, HIGH);
    delay(250);
    digitalWrite(13, LOW);
    delay(250);
  }
}
`
const hand = parseArduino(handWritten)
check(
  'Hand-written C++ parses',
  !hand.error,
  hand.error ? `${hand.error.message} (line ${hand.error.line})` : '',
)
check(
  '...into the right top-level shape',
  !hand.error && hand.blocks.map((b) => b.type).join(',') === 'setVar,whileCompare,motor,ifCompare,repeat',
  hand.error ? '' : hand.blocks.map((b) => b.type).join(','),
)
check(
  '...with count++ read as "add one"',
  !hand.error && hand.blocks[1].body[1].op === '+' && hand.blocks[1].body[1].b.value === 1,
  hand.error ? '' : JSON.stringify(hand.blocks[1]?.body?.[1]),
)
check(
  '...and the for-loop as a repeat of 3',
  !hand.error && hand.blocks[4].times === 3 && hand.blocks[4].body.length === 4,
  hand.error ? '' : JSON.stringify({ times: hand.blocks[4]?.times, n: hand.blocks[4]?.body?.length }),
)

/* ------------------------------------------------------- #define constants */

/*
 * Naming a pin is ordinary Arduino style, and the emitter writes a `#define`
 * header itself — so a student who uses that name in the body is following the
 * file's own lead. The tokeniser used to throw every `#` line away, so
 * `digitalWrite(PIN_13, HIGH)` failed with "I expected a number".
 */
const defineCases = [
  [
    'a defined pin name is a number',
    `#define PIN_13  13  // led
void loop() { digitalWrite(PIN_13, HIGH); }`,
    (b) => b[0].pin === 13,
    (b) => `pin ${b[0]?.pin}`,
  ],
  [
    'any name works, not just PIN_*',
    `#define LEFT_MOTOR 9
#define CRUISE 220
void loop() { setMotor(LEFT_MOTOR, CRUISE); }`,
    (b) => b[0].pin === 9 && b[0].speed === 220,
    (b) => JSON.stringify({ pin: b[0]?.pin, speed: b[0]?.speed }),
  ],
  [
    'a define may name an earlier define',
    `#define A 7
#define B A
void loop() { digitalWrite(B, HIGH); }`,
    (b) => b[0].pin === 7,
    (b) => `pin ${b[0]?.pin}`,
  ],
  [
    'a negative body and a trailing comment',
    `#define REVERSE  -180  // backwards
void loop() { setMotor(9, REVERSE); }`,
    (b) => b[0].speed === -180,
    (b) => `speed ${b[0]?.speed}`,
  ],
  [
    'a define in a comparison is a constant, not a variable',
    `#define MAX 5
void loop() { while (count < MAX) { delay(10); } }`,
    (b) => b[0].b.src === 'num' && b[0].b.value === 5,
    (b) => JSON.stringify(b[0]?.b),
  ],
  [
    'a define as a for-loop limit',
    `#define N 4
void loop() { for (int i = 0; i < N; i++) { delay(10); } }`,
    (b) => b[0].type === 'repeat' && b[0].times === 4,
    (b) => `${b[0]?.type} ${b[0]?.times}`,
  ],
  [
    'a function-like macro is ignored, not misread',
    `#define SQ(x) ((x)*(x))
void loop() { delay(100); }`,
    (b) => b.length === 1 && b[0].type === 'wait',
    (b) => b.map((x) => x.type).join(','),
  ],
  [
    '#include is still skipped',
    `#include <Servo.h>
void loop() { delay(50); }`,
    (b) => b.length === 1 && b[0].type === 'wait',
    (b) => b.map((x) => x.type).join(','),
  ],
  [
    'an undefined name is still a variable, not a number',
    'void loop() { while (count < 5) { delay(10); } }',
    (b) => b[0].a.src === 'var' && b[0].a.name === 'count',
    (b) => JSON.stringify(b[0]?.a),
  ],
]
for (const [name, src, ok, detail] of defineCases) {
  const r = parseArduino(src)
  check(
    name,
    !r.error && ok(r.blocks),
    r.error ? `${r.error.message} (line ${r.error.line})` : detail(r.blocks),
  )
}

// A name nothing defines, where a number is required, must still be refused —
// resolving defines must not turn every unknown word into a silent zero.
const undef = parseArduino('void loop() { digitalWrite(NOPE, HIGH); }')
check('An undefined name where a number is needed still errors', Boolean(undef.error), undef.error?.message ?? 'parsed')

// The whole sketch from the bug report, end to end.
const reported = parseArduino(`#define PIN_13  13  // led

void setup() {
  Serial.begin(9600);
  pinMode(PIN_13, OUTPUT);
}

void loop() {
  digitalWrite(PIN_13, HIGH);
  drive(LEFT, 200);
  drive(RIGHT, 200);
  delay(2000);
  drive(STOP, 0);
  digitalWrite(PIN_13, LOW);
}`)
check(
  'The reported sketch parses',
  !reported.error,
  reported.error ? `${reported.error.message} (line ${reported.error.line})` : '',
)
check(
  '...with both LED writes on pin 13',
  !reported.error &&
    reported.blocks.filter((b) => b.type === 'digitalWrite').every((b) => b.pin === 13),
  reported.error ? '' : JSON.stringify(reported.blocks.filter((b) => b.type === 'digitalWrite').map((b) => b.pin)),
)

// Round trip through the emitter's own header: rewriting the body to use the
// constant the header declares must produce the very same blocks.
const ledBlocks = [
  { id: 'a', type: 'digitalWrite', pin: 13, value: 'HIGH' },
  { id: 'b', type: 'wait', ms: 500 },
  { id: 'c', type: 'digitalWrite', pin: 13, value: 'LOW' },
]
const ledCode = toArduinoCode(ledBlocks, { 13: 'led' })
const viaLiteral = parseArduino(ledCode)
const viaDefine = parseArduino(ledCode.replace(/digitalWrite\(13,/g, 'digitalWrite(PIN_13,'))
check(
  'Round trip: emitted code, literal pins',
  !viaLiteral.error && same(viaLiteral.blocks, ledBlocks),
  viaLiteral.error?.message ?? '',
)
check(
  'Round trip: the same code using its own #define name',
  !viaDefine.error && same(viaDefine.blocks, ledBlocks),
  viaDefine.error ? `${viaDefine.error.message} (line ${viaDefine.error.line})` : '',
)

/* -------------------------------------------------------------- bad input */

const errCases = [
  ['No loop at all', 'void setup() {}'],
  ['Unclosed brace', 'void loop() { delay(100);'],
  ['Nonsense word', 'void loop() { wibble(1); }'],
  ['Missing semicolon', 'void loop() { delay(100) delay(200); }'],
  ['digitalWrite without HIGH/LOW', 'void loop() { digitalWrite(13, MAYBE); }'],
]
for (const [name, src] of errCases) {
  const r = parseArduino(src)
  check(`Rejects: ${name}`, Boolean(r.error) && typeof r.error.line === 'number', r.error?.message ?? 'parsed without complaint')
}
check(
  'Errors never throw, they return',
  (() => {
    try {
      parseArduino('void loop() { if ( } }')
      return true
    } catch {
      return false
    }
  })(),
)

/* ------------------------------------------------ the parsed tree actually runs */

const runnable = parseArduino(`
void loop() {
  total = 0;
  for (int i = 0; i < 4; i++) {
    total = total + 3;
  }
  Serial.println("done");
}
`)
const log = []
if (!runnable.error) {
  const gen = makeRunner(runnable.blocks, {
    now: () => 0,
    digitalWrite: () => {},
    motor: () => {},
    drive: () => {},
    print: (t) => log.push(t),
    distance: () => 100,
  })
  let guard = 0
  while (guard++ < 5000) {
    if (gen.next().done) break
  }
}
check('Parsed code runs on the block interpreter', log.join(',') === 'done', log.join(',') || 'never printed')

// The interpreter and the emitted C++ must agree that these are ints.
const divide = parseArduino('void loop() { r = 7 / 2; Serial.println("x"); }')
let divided = null
if (!divide.error) {
  const gen = makeRunner(divide.blocks, {
    now: () => 0,
    digitalWrite: () => {},
    motor: () => {},
    drive: () => {},
    print: () => {},
    distance: () => 0,
    })
  let guard = 0
  while (guard++ < 100 && !gen.next().done) { /* step */ }
  divided = true
}
check('Integer division does not produce a fraction', divided === true, String(divided))

/* ------------------------------------------------------- tree editing ops */

const tree = [
  makeBlock('wait'),
  { ...makeBlock('repeat'), body: [makeBlock('print')] },
]
const [waitB, repeatB] = tree
const inner = repeatB.body[0]

const moved = moveBlock(tree, waitB.id, repeatB.id, 'body', 0)
check(
  'moveBlock nests a block inside a container',
  moved.length === 1 && findBlock(moved, waitB.id) != null && moved[0].body[0].id === waitB.id,
  moved.map((b) => b.type).join(','),
)

const reordered = moveBlock(tree, repeatB.id, null, 'body', 0)
check(
  'moveBlock reorders at the top level',
  reordered[0].id === repeatB.id && reordered[1].id === waitB.id,
  reordered.map((b) => b.type).join(','),
)

const selfDrop = moveBlock(tree, repeatB.id, inner.id, 'body', 0)
check('moveBlock refuses to drop a container into its own child', same(selfDrop, tree))

const intoItself = moveBlock(tree, repeatB.id, repeatB.id, 'body', 0)
check('moveBlock refuses to drop a block into itself', same(intoItself, tree))

const duped = duplicateBlock(tree, repeatB.id)
check(
  'duplicateBlock copies the subtree next to the original',
  duped.length === 3 && duped[2].type === 'repeat' && duped[2].body.length === 1,
  duped.map((b) => b.type).join(','),
)
check(
  '...with fresh ids all the way down',
  duped[2].id !== repeatB.id && duped[2].body[0].id !== inner.id,
  `${duped[2].id} / ${duped[2].body[0].id}`,
)

/* ------------------------------------------------------------ var hygiene */

check('safeVarName strips punctuation', safeVarName('my count!') === 'mycount', safeVarName('my count!'))
check('safeVarName refuses a leading digit', safeVarName('2fast') === 'fast', safeVarName('2fast'))
check('safeVarName always yields something', safeVarName('!!!') === 'x', safeVarName('!!!'))

const nasty = [{ ...makeBlock('setVar'), name: 'a b;drop()', a: num(1), op: '', b: num(0) }]
const nastyCode = toArduinoCode(nasty, {})
check(
  'A hostile variable name cannot break out into code',
  nastyCode.includes('abdrop = 1;') && !nastyCode.includes('a b;drop()'),
  nastyCode.split('\n').find((l) => l.includes('abdrop')) ?? 'not found',
)

/* ------------------------------------------------------------------- done */

const passed = results.filter((r) => r.startsWith('PASS')).length
console.log(results.join('\n'))
console.log(`\n${passed}/${results.length} PASS`)
process.exit(passed === results.length ? 0 : 1)
